version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: Asia/Tokyo
    groups:
      dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "GitHub Actionsの更新: "
