#!/bin/sh

# 現在のブランチ名を取得
branch=$(git rev-parse --abbrev-ref HEAD)

# `main` ブランチ もしくは `develop` ブランチに git switch した際に git pull を実行する
if [ "$branch" = "main" ] || [ "$branch" = "develop" ]; then
    git pull origin $branch
fi
